---
title: Criaturas mágicas
format:
   html:
      toc: true
      toc-depth: 3
---

# Criaturas mágicas

Habilidad para interactuar con criaturas y plantas mágicas.
Los jugadores pueden domesticar criaturas y/o plantas mágicas, comprender su comportamiento, usarlos para crear soluciones o defensas, etc.

1. Conocimiento: Identificación y clasificación de criaturas y plantas mágicas.
1. Comunicación e Interpretación: Capacidad de interactuar con criaturas mágicas, relacionado con carisma.

## Tabla de contenido

La tabla de a continuación muestra la clasificación que el ministerio de magia (MM) dio a a todas las criaturas basándose en qué tan peligrosas son.

|Complejidad|Clasificación MM|Descripción|
|:----|:----|:----|
|1|X|Aburridas.|
|1|XX|Inofensivas, pueden ser domesticadas.|
|2|XXX|Magos competentes pueden salir adelante.|
|3|XXXX|Peligroso: requiere conocimientos especiales. Magos experimentados pueden manejarlas.|
|4|-|__Respeto mágico__: Capacidad de diálogo y negociación con criaturas mágicas inteligentes que no tienen en general buenas relaciones con los magos.|
|5|XXXXX|Con reputación de asesinar magos: imposible de entrenar o domesticar.|

|Criatura|Clasificación MM|Descripción|
|:----|:----|:----|
|Horklump|X|Criaturas similares a hongos con púas que salen disparadas, capaces de herir a quien se acerque demasiado. Son rosados y con púas rojas.|
|Sapo|X|Sapo común (no mágico), que se usa como mascota, conejillo de indias de encantamientos y como ingrediente de numerosas pociones.|
|Sapo púrpura gigante|X|También conocido como un rana toro, tiene una lengua larga y verde, piel gruesa y oscura y los individuos que los toquen podrían contraer verrugas.|
|Augurey|XX|Ave que predice la lluvia con su canto, anteriormente se pensaba que predice la muerte.|
|Babosa carnívora|XX|Criatura mágica muy similar a la babosa común.|
|Bicornio|XX|Criatura peligrosa parecida a la vaca, y se destacan por tener dos cuernos ondulados y puntiagudos, que son usados como ingredientes para pociones.|
|Bowtruckle|XX|Criatura pequeña que protege los árboles de los cuales se obtienen varitas mágicas.|
|Chizpurfle|XX|Pequeños parásitos de medio centímetro de alto que se parecen a los cangrejos y poseen unos colmillos considerables.|
|Clabbert|XX|Criatura arborícola con un aspecto parecido a un cruce entre un mono y una rana. Posee un diente puntiagudo y un abultamiento en la frente que brilla cuando hay peligro.|
|Diricawl|XX|Ave mágica con un plumaje colorido y brillante conocida anteriormente por muggles como "dodo".|
|Ghoul|XX|Criatura humanoide que se encuentra en lugares lúgubres y húmenos. Son relativamente inofensivos y son, a menudo, vistos como mascotas por las familias mágicas.|
|Grindylow|XX|Demonio acuático, peligroso en el agua, conocido por atacar a los humanos.|
|Gnomo|XX|Los gnomos o enanitos de jardín, son criaturas mágicas conocida comúnmente por infestar los jardines de las casas de magos.|
|Gusarajo|XX|Gusano de unas de veinticinco centímetros de longitud, de color marrón, sin dientes y que come vegetación, especialmente lechuga y repollo. Su moco es utilizado como ingrediente de pociones.|
|Hada|XX|Criaturas humanoides pequeñas y decorativas dotadas de poca inteligencia. Los magos las usan o invocan frecuentemente para que les sirvan de adorno.|
|Jobberknoll|XX|Ave azul moteado que nunca hace ningún ruido hasta el momento antes de morir.|
|Mooncalf|XX|Criatura tímida que sólo sale de su madriguera durante la luna llena. Tiene una piel gris pálida y cuatro piernas delgadas que terminan en grandes pies planos. También tiene ojos saltones que están en la cima de su cabeza.|
|Porlock|XX|Criatura guardián de caballos que vive en el césped. Bien se puede encontrar de anidación en la paja de un establo, o en el medio de la manada que está protegiendo. Los porlocks desconfían de los humanos y se esconden cuando se acercan.|
|Puffskein|XX|Criatura que se encuentra por todo el mundo y es considerado uno de los animales mas domesticables. De forma esférica y cubierto por un pelaje suave, de color natillas, es una criatura dócil que no se opone a que lo mimen ni a que la gente juegue con él lanzándoselo de unas manos a otras.|
|Rámora|XX|Ppez plateado que tiene un fuerte poder mágico para anclar los barcos en su lugar.|
|Serpiente arbórea africana|XX|Serpiente culebrosa, pequeña y venenosa, que es nativa del África subsahariana. Su piel es usada como ingrediente para la fabricación de pociones, como la poción multijugos.|
|Ashwinder|XXX|Serpiente que nace de un fuego mágico descontrolado, pone huevos explosivos.|
|Banshee|XXX|Cuerpo y cara de mujer de largo cabello negro, tienen la cara esquelética y verdosa. Su grito es un augurio de muerte y de sufrimiento.|
|Billywig|XXX|Insecto azul que provoca levitación y mareos con su picadura.|
|Boggart|XXX|Criatura que cambia de forma y se convierte en el peor miedo de quien lo enfrenta.|
|Cangrejo de fuego|XXX|Criatura color gris que se asemeja a una tortuga. Tiene seis patas, y un caparazón cubierto de joyas.|
|Crup|XXX|Criatura parecida a un Terrier Jack Russell, salvo por la cola bífida. Totalmente leal a los hechiceros, feroz con los muggles.|
|Doxy|XXX|Pequeña criatura humanoide de pelaje negro es aconocida por ser una plaga en algunos lugares. Posee hileras de dientes muy afilados y venenosos.|
|Duendecillo|XXX|Pequeñas criaturas mágicas revoltosas y muy traviesas, de color azul brillante, a las que les encanta hacer trucos y bromas.|
|Dugbog|XXX|Criatura de dientes afilados y patas delgadas que se alimenta de animales de mediano tamaño. Tiene predilección por las mandrágoras.|
|Escarbato|XXX|Criatura con un hocico largo y delgado que busca tesoros. Se sienten muy atraídos hacia las cosas brillantes, lo que los hace adecuados para localizar objetos metálicos o con brillo, pero en el proceso pueden llegar a destrozar habitaciones en busca de tesoros.|
|Fwooper|XXX|Ave mágica de colores vibrantes y llamativos. Son conocidos por su canción, la cual induce a la locura.|
|Glumbumble|XXX|Insecto volador gris y peludo que produce una melaza que puede inducir a la melancolía.|
|Hipocampo|XXX|Animal fantástico  que tiene la cabeza y los cuartos delanteros de un caballo, mientras que el resto de su cuerpo está formado por las aletas posteriores de un pez gigantesco.|
|Hipogrifo|XXX|Criatura mitad águila y mitad caballo. Leal si se le trata con respeto.|
|Jarvey|XXX|Criatura mágica que se asemeja a un hurón. El jarvey es capaz de hablar como humano, aunque una verdadera conversación con él es imposible. La criatura utiliza declaraciones y frases cortas, generalmente groseras, muy fluidamente.|
|Knarl|XXX|Criatura que parece un erizo normal, pero ataca se les ofrece comida o si detectan bondad.|
|Kneazle|XXX|Felino similar a un gato grande. Ellos tienen una pelaje moteado y sus orejas y cola son como las de un león. Son excelentes mascotas con sus dueños o con un mago o una bruja de su agrado. Es inteligente e independiente y en ocasiones agresivo. Tienen una extraña habilidad para detectar y desconfiar de personas sospechosas.|
|Leprechaun|XXX|Criatura mágica pequeña y traviesa, aunque no es malicioso. Tienen la reputación de ser bromistas, pero nunca han infligido un daño duradero en un humano.|
|Lobalug|XXX|Criatura marina con forma de pera que expulsa un veneno potente.|
|Mackled o Malaclaw|XXX|Criatura mágica similar a una langosta que nunca debe comerse, ya que su carne no es apta para el consumo humano y puede producir fiebre alta y una erupción verdosa de aspecto desagradable.|
|Moke|XXX|Lagarto capaz de reducir su tamaño hasta hacerse invisible.|
|Murtlap|XXX|Criatura con forma de rata que se encuentra en zonas costeras. Tiene una excrecencia sobre el lomo que se asemeja a una anémona de mar.|
|Plimpy|XXX|Pez pequeño y redondo con dos patas que terminan en dos pies palmeados. Habita en lagos profundos, y se alimenta de caracoles de agua.|
|Pogrebin|XXX|Demonio de un pie de alto y que tiene un cuerpo peludo y una cabeza gris de gran tamaño. Se siente atraído por los humanos y, cuando bajan la guardia por los efectos del pogrebin, este se los come.|
|Salamandra de fuego|XXX|Pequeño anfibio que vive en lugares muy calientes y se alimenta de llamas.|
|Salamandra helada|XXX|Variedad de salamandras mágicas que están estrechamente asociadas con el hielo.|
|Serpiente de mar|XXX|Criatura acuática que se encuentra en varios océanos de todo el mundo. Aunque tienen una apariencia alarmante, no se sabe de ninguna que haya herido a un ser humano.|
|Shrake|XXX|Pez cubierto enteramente de espinas, que son usadas como ingredientes para pociones.|
|Streeler|XXX|Caracol gigante que cambia de color cada hora y su rastro es tan venenoso que quema toda la vegetación por donde pasa.|
|Abraxan|XXXX|Raza de caballo alado. Es gigante y extremadamente poderoso|
|Ave del trueno|XXXX|Enorme ave nativo de Arizona, Estados Unidos. Es capaz que predecir el peligro y produce tormentas eléctricas. Es un pariente cercado del fénix.|
|Demiguise|XXXX|Criatura peluda y pacífica capaz de hacerse invisible y predecir el futuro.|
|Erkling|XXXX|Criatura oriunda de la Selva Negra alemana, cuyo aspecto es similar al de los elfos. Tienen una cara puntiaguda y utiliza un canto seductor para atraer a niños incautos y así comérselos.|
|Erumpent|XXXX|Bestia gris, de gran tamaño y poder, natural de África. Pesa más de una tonelada y, de lejos, puede confundirse con un rinoceronte. Tiene una piel gruesa que repele la mayoría de encantamientos y maleficios, un cuerno largo y puntiagudo sobre el hocico y una cola larga que parece una soga.|
|Esfinge|XXXX|Criatura mágica que tiene la cabeza de una mujer humana sobre el cuerpo de un león. Las esfinges son capaces de comunicarse con los humanos y son conocidas por su amor a los acertijos y enigmas.|
|Fénix|XXXX|Ave mágica de color escarlata del tamaño de un cisne con plumaje rojo y dorado, junto con un pico y garras dorados, ojos negros y una cola tan larga como la de un pavo real. Son seres inmortales, poseyendo la habilidad de curar con sus lágrimas y logrando transportar pesadísimas cargas consigo.|
|Graphorn|XXXX|Criatura mágica agresiva y peligrosa, nativa de las montañas de Europa. Es grande y jorobado, con la piel grisácea/púrpura más dura que la de los dragones. Puede rechazar la mayoría de los hechizos, tiene dos cuernos de oro, y camina sobre cuatro grandes patas.|
|Grifo|XXXX|Criatura mágica que tiene características de varios animales. Posee patas delanteras, alas y cabeza de un águila, y el cuerpo, patas traseras y la cola de un león.|
|Kappa|XXXX|Demonio de agua que se alimenta de la sangre de los humanos.|
|Kelpie|XXXX|Demonio del agua que puede adoptar varias formas, aunque lo más frecuente es que aparezca con el aspecto de un caballo con crines de junco. Seduce a los incautos para que lo monten y, después, los lleva directamente al fondo del rio o del lago, donde los devora.|
|Occamy|XXXX|Criatura emplumada de dos patas y cuerpo de serpiente con alas que pueden alcanzar hasta cuatro metros y medio de altura. El occamy es agresivo con todos los que se le acercan y se alimenta de insectos, ratas, pájaros y ocasionalmente monos.|
|Runespoor|XXXX|Serpiente de tres cabezas cuya longitud varía entre un metro y ochenta centímetros y dos metros y diez centímetros. Debido a su piel, de un naranja subido con rayas negras, la runespoor es muy fácil de distinguir.|
|Siempredetrás|XXXX|También conocido como escondedetrás, es una criatura creada de manera accidental por magos. Es nocturno y puede esconderse detrás de casi cualquier cosa que encuentre para ocultarse. Sus presas preferidas son los humanos.|
|Snallygaster|XXXX|Criatura parecida a un dragón que ha aparecido en muchos periódicos muggle y es bien conocido que compite con el monstruo del Lago Ness.|
|Snidget dorado|XXXX|Pequeño pájaro mágico dorado muy escaso y protegido, con alas completamente giratorias, mejor conocida por su uso temprano en el juego mágico de quidditch, eventualmente siendo reemplazada por la snitch dorada.|
|Tebo|XXXX|Criatura mágica similar a un jabalí de color ceniza que se encuentra en el Zaire y el Congo. Tiene la habilidad de volverse invisible, dificultando su captura y evasión cuando embiste, es muy peligroso.|
|Thestral|XXXX|Caballo alado con un cuerpo esquelético, rostro de rasgos reptilianos y unas alas de aspecto curtido que recuerdan a las de un murciélago. Visibles solo para quienes han presenciado la muerte.|
|Unicornio|XXXX|Criatura blanca, equina con un solo cuerno en la frente. Desde su pelo hasta su sangre, esta criatura es poseedora de numerosas propiedades mágicas.|
|Uro|XXXX|Bestia mágica nativa de hábitat desértico extremadamente rara, parecida a un buey gigante con piel dorada.|
|Yeti|XXXX|Criatura humanoide de color blanco, peludo y está cubierto de nieve que llega a medir hasta cuatro metros y medio de altura.|
|Acromántula|XXXXX|Monstruosa araña gigante de ocho ojos capaz de hablar como las personas.|
|Basilisco|XXXXX|Serpiente gigante cuya mirada mata instantáneamente.|
|Chimera|XXXXX|Bestia híbrida extremadamente peligrosa, con cabeza de león, cuerpo de cabra y cola de dragón.|
|Dragón|XXXXX|Gigantesco reptil alado y con aliento de fuego. Considerado terrible y muy destructivo.|
|Inferi|XXXXX|Cadáveres reanimados que obedecen órdenes oscuras.|
|Licántropo (hombre lobo) en forma de bestia|XXXXX|Personas que llevan consigo la enfermedad de la licantropía. Tienen la capacidad de transformarse en un lobo en apariencia y naturaleza, al haber sido mordidas por un hombre lobo en su forma de lobo en el momento de la luna llena. El hombre lobo se transforma bajo la influencia de esta.|
|Mantícora|XXXXX|Animal fantástico que tiene la cabeza de un humano, el cuerpo de un león y la cola de un escorpión que mataría a cualquiera instantáneamente con su aguijón. La piel de una mantícora repele todos los encantamientos conocidos.|
|Nundu|XXXXX|Mamífero gigante similar a un leopardo que se mueve silenciosamente pese a su gran tamaño, y es considerado la criatura más peligrosa del mundo. Su aliento causa enfermedades tan virulentas que pueden aniquilar poblaciones enteras.|
|Lethifold|XXXXX|Criatura negra que se desliza como una capa y que asfixia y devora a sus víctimas mientras duermen.|
|Quimera|XXXXX|Criatura cruel y sanguinaria con cabeza de león, cuerpo de cabra y cola de dragón.|
|Quintaped|XXXXX|Bestia carnivora sumamente peligrosa que muestra predilección por la carne humana. Su cuerpo achatado está cubierto con grueso pelo castaño rojizo, igual que sus cinco patas de pies deformes.|
|Serpiente cornuda|XXXXX|Serpiente con cuernos de tamaño descomunar con numerosas propiedades mágicas.|
|Troll|XXXXX|Gigante extremadamente fuerte pero de inteligencia limitada. Muy peligroso.|
|Wampus|XXXXX|Felino mágico nativo de los montes Apalaches de Estados Unidos. Esta criatura posee tres pares de patas. Sus amarillos ojos tienen la capacidad de hipnotizar y también tienen el poder de la legeremancia. |

Los __dragones__ son gigantescos reptiles alados y con aliento de fuego. Siempre han sido considerados terribles y muy destructivos, se pueden encontrar alrededor de todo el mundo.
La siguiente lista desglosa los tipos de dragón registrados y su localización.

|Dragón|Descripción|
|:----|:----|
|Bola de fuego catalán|El bola de fuego catalán es una raza de dragón autóctona de España. Casi extinto.|
|Bola de fuego chino|El bola de fuego chino es el único dragón oriental que existe y tiene un aspecto especialmente llamativo. De escamas suaves y escarlatas, tiene una hilera de astas doradas alrededor de la cara, un hocico chato y ojos sumamente protuberantes. El bola de fuego se ganó ese nombre por la llama con forma de hongo que sale de sus narinas cuando está enfadado.|
|Colacuerno húngaro|El colacuerno húngaro es un dragón nativo de Hungría y se considera la raza más peligrosa entre los dragones. Tiene escamas negras, una cola con púas, y los cuernos de bronce que sobresalen de su cabeza. Tiene ojos amarillos con pupilas verticales. Su rugido es como un maullido y gritos chirriantes, y su llama puede llegar a unos quince metros.|
|Galés verde común|El galés verde común es una de las diez especies de dragón del mundo mágico. Es de color verde, tiene un rugido muy caracteristico, incluso melodioso y lanza finos chorros de llamas por su boca.|
|Hocicorto sueco|El hocicorto sueco es un atractivo dragón azul plateado cuya piel es buscada para la fabricación de guantes y escudos protectores. La llama que sale de sus fosas nasales es de un azul brillante y puede reducir la madera y los huesos a cenizas en cuestión de segundos.|
|Hocilargo portugués|El hocilargo portugués es una raza de dragón que se encuentra generalmente en el norte de Portugal, alrededor de Gerês. Tiene escamas de color verde claro y ojos negros.|
|Ironbelly ucraniano|El ironbelly ucraniano es un dragón nativo de Ucrania. Se dice que es la especie de dragón que más ha vivido en el mundo.|
|Opaleye de las Antípodas|Se considera el dragón mas hermoso que existe, con escamas iridiscentes y nacaradas, ojos sin pupilas multicolor y centelleantes, de donde saca su nombre. Su llama es de un escarlata intenso. Habita generalmente en valles en detrimento de las montañas, lo que es inusual en esta especie.|
|Ridgeback noruego|El ridgeback noruego es un dragón nativo de Noruega, y su hábitat son las montañas del norte. Se asemeja al colacuerno húngaro a excepción de sus crestas negras en la espalda y su actitud menos hostil. Tiene colmillos venenosos, y su alimento preferido son los mamíferos grandes, incluyendo a los mamíferos de agua, que son inusuales para un dragón.|
|Vipertooth peruano|El vipertooth peruano tiene escamas lisas y de color cobrizo. Dispone de marcas y cuernos cortos en la cabeza y, al igual que el Ridgeback noruego, sus colmillos son venenosos. Es la raza de dragón más pequeña y más rápida conocida.|

Otras criaturas mágicas inteligentes que no son consideradas bestias o animales fantásticos están descritas a continuación, con la fortuna que el jugador con __4__ puntos en _criaturas_ cuenta con el __Respeto mágico__ y podrá entablar relaciones con ellos, contar con su confianza (nada común entre los magos y brujas) y con conocimientos de su cultura y constumbres.

|Ser|Descripción|
|:----|:----|
|Arpía|Ser come-niños que parece una bruja vieja con muchas verrugas. Tienen sólo magia rudimentaria, similar a la observada en los trolls.|
|Centauros|Criaturas mágicas de clasificación XXXX por el MM, cuya cabeza, torso y brazos parecen humanos y estan unidos a la parte inferior del cuerpo de un caballo. Sin embargo, son su propia especie individual y, por tanto, no son Híbridos. También tienen una rica historia y son conocidos por tener un talento natural en tiro con arco, magia curativa, adivinación y astronomía. A pesar de poseer "inteligencia humana", fueron clasificados como Bestias por el MM a petición propia, ya que no estaban contentos de tener que compartir el estatus de Ser con arpías y vampiros, conocidas criaturas oscuras.|
|Duendes|Raza muy inteligente de pequeños humanoides con dedos y pies largos que coexisten con los magos y brujas. Hablan en un idioma conocido como duendigonza, y son buenos orfebres notables por su platería; incluso acuñan monedas como dinero mágico. Debido a sus habilidades con el dinero y las finanzas, controlan la economía mágica en gran medida y administran el banco mágico Gringotts. Tienen su tipo de magia y pueden hacer magia sin varita. Su esperanza de vida supera los 100 años.|
|Elfos domésticos|También conocidos como elfos,son criaturas mágica inmensamente devotas y leales a la persona designada como su amo. Sirven a magos y brujas y generalmente se encuentran bajo el empleo de viejas familias de magos que residen en establecimientos elaborados, como mansiones, y deben hacer todo lo que sus amos mandan a menos que sean liberados. Un elfo doméstico solo puede ser liberado cuando su amo les entrega ropa. La mayoríano soportan la idea de ser libres. Tienen su propia marca de magia si Su esperanza de vida data de cientos de años, sin superar los 1000 años.|
|Gente del agua|Criaturas mágicas con inteligencia semi-humana que viven en el fondo del agua. Hay gente del agua por todo el mundo, y varían en apariencia casi tanto como los seres humanos. Sus prácticas y costumbres tienen un halo de misterio equiparable al que rodea a los centauros, aunque aquellos magos que han aprendido sirenio hablan de comunidades sumamente organizadas que varían de tamaño según el hábitat y que, en algunos casos, disponen de viviendas construidas con mucho esmero. También se sabe que domestican criaturas tales como grindylows e hipocampos. Al igual que los centauros, la gente del agua ha rechazado el estatus de seres en favor de la clasificación de bestias, ya que estaban en contra de compartir el estatus con arpías y vampiros.|
|Gigantes|Homínidos muy grande que potencialmente puede llegar a unos veinte metros de altura, y parecen seres humanos de gran tamaño. Los gigantes no son tan inteligentes como los magos y las brujas, pero tienen su propio lenguaje, cultura y sociedad. Una tribu de gigantes es dirigida por el gigante mayor, conocido como Gurg. Su esperanza de vida supera los 200 años.|
|Licántropos (hombres lobo) en forma humana|Personas que llevan consigo la enfermedad de la licantropía. Tienen la capacidad de transformarse en un lobo en apariencia y naturaleza, al haber sido mordidas por un hombre lobo en su forma de lobo en el momento de la luna llena. El hombre lobo se transforma bajo la influencia de esta.|
|Muggles|Comunidad de gente no mágica. Su esperanza de vida no supera los 100 años.|
|Squibs|Gente no mágica nacida en familias con sangre mágica. Su esperanza de vida no supera los 100 años.|
|Vampiros|Humanoides mágicos famosos por morder a las personas en el cuello y chuparles la sangre. De apariencia pálida y demacrada,poseen colmillos afilados para perforar las gargantas de sus víctimas. Su esperanza de vida no supera los 200 años.|
|Veelas|Raza de semi-humanas remanentes de las sirenas. De apariencia de muy jóvenes y bellas mujeres, poseen una danza mágicamente seductora para la mayoría de los hombres. Cuando se enojan, sus rostros se convierten en algo parecido a la cabeza de un ave con picos largos y filosos y con largas plumas que nacen de sus hombros, también pueden lanzar bolas de fuego de sus manos.|

## Plantas mágicas

## Tabla de contenido

La tabla de a continuación muestra las plantas mágicas y los puntos de _criaturas y plantas_ necesarios para su domesticación, uso y cuidado.

|Planta|Complejidad|Descripción|
|:----|:----|:----|
|Branquialgas|1|Cuando es ingerida, esta planta causa el crecimiento de branquias y dedos palmeados, y así se hace posible respirar y nadar bajo el agua por aproximadamente una hora, dependiendo de si el usuario está en agua dulce o salada.|
|Flor voladora|1|Planta que a la vista se asemeja al lazo del diablo, pero es inofensiva.1|
|Geranio colmilludo|1|Planta de jardín común que se sabe que muerde o ataca si no se cuida. No es carnívora, pero sus  afilados colmillos causan dolos a sus víctimas.|
|Chasquichirridos|2|Planta mágica con la capacidad de moverse y hacer ruido. También es semi-sensible teniendo la capacidad de sentir tanto dolor como placer.|
|Mimbulus mimbletonia|2|Cactus con furúnculos en vez de espinas; rocía baba maloliente en un gran radio al golpearla.|
|Bubotubérculo|3|Plantas gruesas y negras como babosas que crecen verticalmente de la tierra. Es normal que se retuerzan y están cubiertas de bultos llenos de pus. El pus parece ser ácido y dañará la carne si no se trata, pero si es destilado puede ser un ingrediente para pociones útil.|
|Mandrágora|3|Planta cuyo​ tubérculo se parece a un bebé cuando es joven. Sus gritos pueden matar cuando está madura. Una poción hecha con mandrágoras maduras puede curar a las víctimas que han sido petrificadas.|
|Planta punta espinosa|3|Planta con pinchos que, al detectar alguna amenaza, se disparan por todos lados.|
|Snargaluff|4|Planta con la apariencia de una cepa nudosa, pero esconde peligrosas enredaderas cubiertas de espinas que atacan cuando se les provoca y por lo general es mejor manejado por más de una persona.|
|Tentácula venenosa|4|Planta mágica que posee una serie de tentáculos espinosos (a los que llaman dientes) de color rojo oscuro. Sus tentáculos son como los tentáculos de un pulpo con pequeñas solapas por donde se alimentan.|
|Lazo del diablo|5|Planta parecida a la enredadera o a la flor voladora, que  atrapa a quien cae en ella y puede llegar a matar. Para soltarse es necesario relajarse o usar un hechizo como el lumos solem, que la hace retroceder. La luz es mortal para esta planta.|
|Sauce Boxeador|5|Variedad mágica del sauce común. Estos sensibles y fuertes árboles tienen la capacidad de poder mover sus ramas a voluntad, al igual que parte de su tronco, para poder proporcionar golges a quien sea que se le acerque.|
